// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_notebooks_upload_sourceSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_notebooks-upload_source'
} as const;

export const CitationPublicSchema = {
    properties: {
        chunk_id: {
            type: 'string',
            format: 'uuid',
            title: 'Chunk Id'
        },
        ordinal: {
            type: 'integer',
            title: 'Ordinal'
        },
        quote: {
            type: 'string',
            title: 'Quote'
        },
        source_display_name: {
            type: 'string',
            title: 'Source Display Name'
        },
        page_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Number'
        }
    },
    type: 'object',
    required: ['chunk_id', 'ordinal', 'quote', 'source_display_name', 'page_number'],
    title: 'CitationPublic'
} as const;

export const ConversationCreateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        }
    },
    type: 'object',
    title: 'ConversationCreate'
} as const;

export const ConversationDetailPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        notebook_id: {
            type: 'string',
            format: 'uuid',
            title: 'Notebook Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        is_pinned: {
            type: 'boolean',
            title: 'Is Pinned',
            default: false
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        messages: {
            items: {
                '$ref': '#/components/schemas/ConversationMessagePublic'
            },
            type: 'array',
            title: 'Messages'
        }
    },
    type: 'object',
    required: ['id', 'notebook_id', 'title', 'created_at', 'updated_at', 'messages'],
    title: 'ConversationDetailPublic'
} as const;

export const ConversationMessageCreateSchema = {
    properties: {
        content: {
            type: 'string',
            maxLength: 4000,
            minLength: 1,
            title: 'Content'
        },
        mode: {
            type: 'string',
            enum: ['grounded', 'hybrid', 'knowledge'],
            title: 'Mode',
            default: 'grounded'
        },
        source_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array',
                    maxItems: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Ids'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'ConversationMessageCreate'
} as const;

export const ConversationMessagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        suggestions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Suggestions',
            default: []
        },
        citations: {
            items: {
                '$ref': '#/components/schemas/CitationPublic'
            },
            type: 'array',
            title: 'Citations'
        }
    },
    type: 'object',
    required: ['id', 'role', 'content', 'created_at', 'citations'],
    title: 'ConversationMessagePublic'
} as const;

export const ConversationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        notebook_id: {
            type: 'string',
            format: 'uuid',
            title: 'Notebook Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        is_pinned: {
            type: 'boolean',
            title: 'Is Pinned',
            default: false
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'notebook_id', 'title', 'created_at', 'updated_at'],
    title: 'ConversationPublic'
} as const;

export const ConversationUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        is_pinned: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Pinned'
        }
    },
    type: 'object',
    title: 'ConversationUpdate'
} as const;

export const ConversationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ConversationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ConversationsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModelFetchRequestSchema = {
    properties: {
        base_url: {
            type: 'string',
            maxLength: 1000,
            title: 'Base Url',
            default: ''
        },
        api_key: {
            type: 'string',
            maxLength: 1000,
            title: 'Api Key',
            default: ''
        },
        api_format: {
            type: 'string',
            maxLength: 32,
            title: 'Api Format',
            default: 'openai'
        }
    },
    type: 'object',
    title: 'ModelFetchRequest',
    description: `Fetch available model IDs from an OpenAI-compatible /models endpoint.
Empty base_url/api_key fall back to the server's configured provider.
\`api_format\` follows the ProviderConfig convention ("openai" | "openai_v1").`
} as const;

export const ModelInfoPublicSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'ModelInfoPublic'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NotebookCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'NotebookCreate'
} as const;

export const NotebookOverviewPublicSchema = {
    properties: {
        summary: {
            type: 'string',
            title: 'Summary'
        },
        topics: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Topics'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['summary', 'topics'],
    title: 'NotebookOverviewPublic'
} as const;

export const NotebookPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        is_pinned: {
            type: 'boolean',
            title: 'Is Pinned',
            default: false
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id', 'created_at', 'updated_at'],
    title: 'NotebookPublic'
} as const;

export const NotebookUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_pinned: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Pinned'
        }
    },
    type: 'object',
    title: 'NotebookUpdate'
} as const;

export const NotebooksPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NotebookPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'NotebooksPublic'
} as const;

export const ResendVerificationRequestSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'ResendVerificationRequest'
} as const;

export const RetrievedChunkPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        source_id: {
            type: 'string',
            format: 'uuid',
            title: 'Source Id'
        },
        source_display_name: {
            type: 'string',
            title: 'Source Display Name'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        page_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Number'
        },
        score: {
            type: 'number',
            title: 'Score'
        }
    },
    type: 'object',
    required: ['id', 'source_id', 'source_display_name', 'content', 'page_number', 'score'],
    title: 'RetrievedChunkPublic'
} as const;

export const RetrievedChunksPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RetrievedChunkPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'RetrievedChunksPublic'
} as const;

export const SearchRequestSchema = {
    properties: {
        query: {
            type: 'string',
            maxLength: 4000,
            minLength: 1,
            title: 'Query'
        },
        limit: {
            type: 'integer',
            maximum: 10,
            minimum: 1,
            title: 'Limit',
            default: 5
        }
    },
    type: 'object',
    required: ['query'],
    title: 'SearchRequest'
} as const;

export const SignupResultSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        is_email_verified: {
            type: 'boolean',
            title: 'Is Email Verified'
        }
    },
    type: 'object',
    required: ['email', 'is_email_verified'],
    title: 'SignupResult',
    description: `Response for public self-signup.

Deliberately carries no account id or timestamps, and \`is_email_verified\`
reflects the mail-backend state (whether verification is required at all),
never the actual account — so the endpoint cannot be used to enumerate
registered addresses (a new signup and an existing account return the exact
same body).`
} as const;

export const SourcePublicSchema = {
    properties: {
        display_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Display Name'
        },
        media_type: {
            type: 'string',
            maxLength: 100,
            title: 'Media Type'
        },
        file_size_bytes: {
            type: 'integer',
            minimum: 0,
            title: 'File Size Bytes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        notebook_id: {
            type: 'string',
            format: 'uuid',
            title: 'Notebook Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        page_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Count'
        },
        char_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Char Count'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        processed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Processed At'
        }
    },
    type: 'object',
    required: ['display_name', 'media_type', 'file_size_bytes', 'id', 'notebook_id', 'status', 'error_message', 'page_count', 'char_count', 'created_at', 'processed_at'],
    title: 'SourcePublic'
} as const;

export const SourcesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SourcePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SourcesPublic'
} as const;

export const StudyFaqPublicSchema = {
    properties: {
        question: {
            type: 'string',
            title: 'Question'
        },
        answer: {
            type: 'string',
            title: 'Answer'
        }
    },
    type: 'object',
    required: ['question', 'answer'],
    title: 'StudyFaqPublic'
} as const;

export const StudyGuidePublicSchema = {
    properties: {
        sections: {
            items: {
                '$ref': '#/components/schemas/StudySectionPublic'
            },
            type: 'array',
            title: 'Sections'
        },
        faqs: {
            items: {
                '$ref': '#/components/schemas/StudyFaqPublic'
            },
            type: 'array',
            title: 'Faqs'
        }
    },
    type: 'object',
    required: ['sections', 'faqs'],
    title: 'StudyGuidePublic'
} as const;

export const StudySectionPublicSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['title', 'content'],
    title: 'StudySectionPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserProviderSettingsCreateSchema = {
    properties: {
        chat_base_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chat Base Url'
        },
        chat_api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chat Api Key'
        },
        chat_model: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chat Model'
        },
        chat_api_format: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chat Api Format'
        },
        embedding_base_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Embedding Base Url'
        },
        embedding_api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Embedding Api Key'
        },
        embedding_model: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Embedding Model'
        },
        embedding_api_format: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Embedding Api Format'
        }
    },
    type: 'object',
    title: 'UserProviderSettingsCreate',
    description: 'Incoming per-user provider settings; empty api_key fields keep the stored key.'
} as const;

export const UserProviderSettingsPublicSchema = {
    properties: {
        chat_base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chat Base Url'
        },
        chat_api_key: {
            type: 'string',
            title: 'Chat Api Key',
            default: ''
        },
        chat_model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chat Model'
        },
        chat_api_format: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chat Api Format'
        },
        embedding_base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Embedding Base Url'
        },
        embedding_api_key: {
            type: 'string',
            title: 'Embedding Api Key',
            default: ''
        },
        embedding_model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Embedding Model'
        },
        embedding_api_format: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Embedding Api Format'
        },
        cooldown_until: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooldown Until'
        }
    },
    type: 'object',
    title: 'UserProviderSettingsPublic',
    description: `Settings returned to the client; API keys are always masked.

\`cooldown_until\` is set when the user has configured their own API key and
is still inside the switch-back window — clearing the config to revert to
the server default is blocked until that time.`
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        is_email_verified: {
            type: 'boolean',
            title: 'Is Email Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        current_password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Password'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UserUsagePublicSchema = {
    properties: {
        chat_tokens: {
            type: 'integer',
            title: 'Chat Tokens'
        },
        chat_quota: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chat Quota'
        },
        chat_source: {
            type: 'string',
            enum: ['server', 'user', 'none'],
            title: 'Chat Source',
            default: 'none'
        },
        embedding_chars: {
            type: 'integer',
            title: 'Embedding Chars'
        },
        embedding_quota: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Embedding Quota'
        },
        embedding_source: {
            type: 'string',
            enum: ['server', 'user', 'none'],
            title: 'Embedding Source',
            default: 'none'
        },
        period_start: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Period Start'
        }
    },
    type: 'object',
    required: ['chat_tokens', 'embedding_chars'],
    title: 'UserUsagePublic',
    description: `Usage counters plus the free allowance that applies to each dimension.

\`chat_quota\`/\`embedding_quota\` are None when the user brings their own API
key (unlimited) or when nothing is configured (cannot be used at all).
\`*_source\` tells the client who is billed: "server", "user" or "none".`
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VerifyEmailRequestSchema = {
    properties: {
        token: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Token'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'VerifyEmailRequest'
} as const;