// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ConversationsReadConversationData, ConversationsReadConversationResponse, ConversationsStreamMessageData, ConversationsStreamMessageResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, NotebooksReadNotebooksData, NotebooksReadNotebooksResponse, NotebooksCreateNotebookData, NotebooksCreateNotebookResponse, NotebooksReadNotebookData, NotebooksReadNotebookResponse, NotebooksUpdateNotebookData, NotebooksUpdateNotebookResponse, NotebooksDeleteNotebookData, NotebooksDeleteNotebookResponse, NotebooksReadSourcesData, NotebooksReadSourcesResponse, NotebooksUploadSourceData, NotebooksUploadSourceResponse, NotebooksReadConversationsData, NotebooksReadConversationsResponse, NotebooksCreateConversationData, NotebooksCreateConversationResponse, NotebooksSearchNotebookData, NotebooksSearchNotebookResponse, NotebooksRemoveSourceData, NotebooksRemoveSourceResponse, NotebooksRetrySourceData, NotebooksRetrySourceResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class ConversationsService {
    /**
     * Read Conversation
     * @param data The data for the request.
     * @param data.conversationId
     * @returns ConversationDetailPublic Successful Response
     * @throws ApiError
     */
    public static readConversation(data: ConversationsReadConversationData): CancelablePromise<ConversationsReadConversationResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/conversations/{conversation_id}',
            path: {
                conversation_id: data.conversationId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Stream Message
     * @param data The data for the request.
     * @param data.conversationId
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static streamMessage(data: ConversationsStreamMessageData): CancelablePromise<ConversationsStreamMessageResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/conversations/{conversation_id}/messages/stream',
            path: {
                conversation_id: data.conversationId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class NotebooksService {
    /**
     * Read Notebooks
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns NotebooksPublic Successful Response
     * @throws ApiError
     */
    public static readNotebooks(data: NotebooksReadNotebooksData = {}): CancelablePromise<NotebooksReadNotebooksResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/notebooks/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Notebook
     * @param data The data for the request.
     * @param data.requestBody
     * @returns NotebookPublic Successful Response
     * @throws ApiError
     */
    public static createNotebook(data: NotebooksCreateNotebookData): CancelablePromise<NotebooksCreateNotebookResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/notebooks/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Notebook
     * @param data The data for the request.
     * @param data.notebookId
     * @returns NotebookPublic Successful Response
     * @throws ApiError
     */
    public static readNotebook(data: NotebooksReadNotebookData): CancelablePromise<NotebooksReadNotebookResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/notebooks/{notebook_id}',
            path: {
                notebook_id: data.notebookId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Notebook
     * @param data The data for the request.
     * @param data.notebookId
     * @param data.requestBody
     * @returns NotebookPublic Successful Response
     * @throws ApiError
     */
    public static updateNotebook(data: NotebooksUpdateNotebookData): CancelablePromise<NotebooksUpdateNotebookResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/notebooks/{notebook_id}',
            path: {
                notebook_id: data.notebookId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Notebook
     * @param data The data for the request.
     * @param data.notebookId
     * @returns string Successful Response
     * @throws ApiError
     */
    public static deleteNotebook(data: NotebooksDeleteNotebookData): CancelablePromise<NotebooksDeleteNotebookResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/notebooks/{notebook_id}',
            path: {
                notebook_id: data.notebookId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Sources
     * @param data The data for the request.
     * @param data.notebookId
     * @param data.skip
     * @param data.limit
     * @returns SourcesPublic Successful Response
     * @throws ApiError
     */
    public static readSources(data: NotebooksReadSourcesData): CancelablePromise<NotebooksReadSourcesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/notebooks/{notebook_id}/sources/',
            path: {
                notebook_id: data.notebookId
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Upload Source
     * @param data The data for the request.
     * @param data.notebookId
     * @param data.formData
     * @returns SourcePublic Successful Response
     * @throws ApiError
     */
    public static uploadSource(data: NotebooksUploadSourceData): CancelablePromise<NotebooksUploadSourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/notebooks/{notebook_id}/sources/',
            path: {
                notebook_id: data.notebookId
            },
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Conversations
     * @param data The data for the request.
     * @param data.notebookId
     * @param data.skip
     * @param data.limit
     * @returns ConversationsPublic Successful Response
     * @throws ApiError
     */
    public static readConversations(data: NotebooksReadConversationsData): CancelablePromise<NotebooksReadConversationsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/notebooks/{notebook_id}/conversations/',
            path: {
                notebook_id: data.notebookId
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Conversation
     * @param data The data for the request.
     * @param data.notebookId
     * @param data.requestBody
     * @returns ConversationPublic Successful Response
     * @throws ApiError
     */
    public static createConversation(data: NotebooksCreateConversationData): CancelablePromise<NotebooksCreateConversationResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/notebooks/{notebook_id}/conversations/',
            path: {
                notebook_id: data.notebookId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Search Notebook
     * @param data The data for the request.
     * @param data.notebookId
     * @param data.requestBody
     * @returns RetrievedChunksPublic Successful Response
     * @throws ApiError
     */
    public static searchNotebook(data: NotebooksSearchNotebookData): CancelablePromise<NotebooksSearchNotebookResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/notebooks/{notebook_id}/search',
            path: {
                notebook_id: data.notebookId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Remove Source
     * @param data The data for the request.
     * @param data.notebookId
     * @param data.sourceId
     * @returns string Successful Response
     * @throws ApiError
     */
    public static removeSource(data: NotebooksRemoveSourceData): CancelablePromise<NotebooksRemoveSourceResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/notebooks/{notebook_id}/sources/{source_id}',
            path: {
                notebook_id: data.notebookId,
                source_id: data.sourceId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Retry Source
     * @param data The data for the request.
     * @param data.notebookId
     * @param data.sourceId
     * @returns SourcePublic Successful Response
     * @throws ApiError
     */
    public static retrySource(data: NotebooksRetrySourceData): CancelablePromise<NotebooksRetrySourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/notebooks/{notebook_id}/sources/{source_id}/retry',
            path: {
                notebook_id: data.notebookId,
                source_id: data.sourceId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}