// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_notebooks_upload_source = {
    file: string;
};

export type CitationPublic = {
    chunk_id: string;
    ordinal: number;
    quote: string;
    source_display_name: string;
    page_number: (number | null);
};

export type ConversationCreate = {
    title?: (string | null);
};

export type ConversationDetailPublic = {
    id: string;
    notebook_id: string;
    title: string;
    created_at: string;
    updated_at: string;
    messages: Array<ConversationMessagePublic>;
};

export type ConversationMessageCreate = {
    content: string;
};

export type ConversationMessagePublic = {
    id: string;
    role: string;
    content: string;
    created_at: string;
    citations: Array<CitationPublic>;
};

export type ConversationPublic = {
    id: string;
    notebook_id: string;
    title: string;
    created_at: string;
    updated_at: string;
};

export type ConversationsPublic = {
    data: Array<ConversationPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotebookCreate = {
    title: string;
    description?: (string | null);
};

export type NotebookPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type NotebooksPublic = {
    data: Array<NotebookPublic>;
    count: number;
};

export type NotebookUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RetrievedChunkPublic = {
    id: string;
    source_id: string;
    source_display_name: string;
    content: string;
    page_number: (number | null);
    score: number;
};

export type RetrievedChunksPublic = {
    data: Array<RetrievedChunkPublic>;
};

export type SearchRequest = {
    query: string;
    limit?: number;
};

export type SourcePublic = {
    display_name: string;
    media_type: string;
    file_size_bytes: number;
    id: string;
    notebook_id: string;
    status: string;
    error_message: (string | null);
    page_count: (number | null);
    char_count: (number | null);
    created_at: string;
    processed_at: (string | null);
};

export type SourcesPublic = {
    data: Array<SourcePublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ConversationsReadConversationData = {
    conversationId: string;
};

export type ConversationsReadConversationResponse = (ConversationDetailPublic);

export type ConversationsStreamMessageData = {
    conversationId: string;
    requestBody: ConversationMessageCreate;
};

export type ConversationsStreamMessageResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NotebooksReadNotebooksData = {
    limit?: number;
    skip?: number;
};

export type NotebooksReadNotebooksResponse = (NotebooksPublic);

export type NotebooksCreateNotebookData = {
    requestBody: NotebookCreate;
};

export type NotebooksCreateNotebookResponse = (NotebookPublic);

export type NotebooksReadNotebookData = {
    notebookId: string;
};

export type NotebooksReadNotebookResponse = (NotebookPublic);

export type NotebooksUpdateNotebookData = {
    notebookId: string;
    requestBody: NotebookUpdate;
};

export type NotebooksUpdateNotebookResponse = (NotebookPublic);

export type NotebooksDeleteNotebookData = {
    notebookId: string;
};

export type NotebooksDeleteNotebookResponse = ({
    [key: string]: (string);
});

export type NotebooksReadSourcesData = {
    limit?: number;
    notebookId: string;
    skip?: number;
};

export type NotebooksReadSourcesResponse = (SourcesPublic);

export type NotebooksUploadSourceData = {
    formData: Body_notebooks_upload_source;
    notebookId: string;
};

export type NotebooksUploadSourceResponse = (SourcePublic);

export type NotebooksReadConversationsData = {
    limit?: number;
    notebookId: string;
    skip?: number;
};

export type NotebooksReadConversationsResponse = (ConversationsPublic);

export type NotebooksCreateConversationData = {
    notebookId: string;
    requestBody: ConversationCreate;
};

export type NotebooksCreateConversationResponse = (ConversationPublic);

export type NotebooksSearchNotebookData = {
    notebookId: string;
    requestBody: SearchRequest;
};

export type NotebooksSearchNotebookResponse = (RetrievedChunksPublic);

export type NotebooksRemoveSourceData = {
    notebookId: string;
    sourceId: string;
};

export type NotebooksRemoveSourceResponse = ({
    [key: string]: (string);
});

export type NotebooksRetrySourceData = {
    notebookId: string;
    sourceId: string;
};

export type NotebooksRetrySourceResponse = (SourcePublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);