"""add user password_changed_at

Revision ID: f864ffa3c8c6
Revises: 87c42fcd0445
Create Date: 2026-08-03 00:22:21.594912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f864ffa3c8c6'
down_revision = '87c42fcd0445'
branch_labels = None
depends_on = None


def upgrade():
    # Only the column is intended here. Hand-written (not autogenerated):
    # autogenerate compares against the live DB and would also emit unrelated
    # drift (pgvector index/constraint drops) that must not ship.
    op.add_column(
        'user',
        sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    )


def downgrade():
    op.drop_column('user', 'password_changed_at')
